// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview An AI-powered assistant to answer user questions about the application.
 *
 * - aiHelpAssistant - A function that provides guidance and answers questions about the application.
 * - AiHelpAssistantInput - The input type for the aiHelpAssistant function.
 * - AiHelpAssistantOutput - The return type for the aiHelpAssistant function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AiHelpAssistantInputSchema = z.object({
  query: z.string().describe('The user query about the application.'),
});
export type AiHelpAssistantInput = z.infer<typeof AiHelpAssistantInputSchema>;

const AiHelpAssistantOutputSchema = z.object({
  answer: z.string().describe('The answer to the user query.'),
});
export type AiHelpAssistantOutput = z.infer<typeof AiHelpAssistantOutputSchema>;

export async function aiHelpAssistant(input: AiHelpAssistantInput): Promise<AiHelpAssistantOutput> {
  return aiHelpAssistantFlow(input);
}

const prompt = ai.definePrompt({
  name: 'aiHelpAssistantPrompt',
  input: {schema: AiHelpAssistantInputSchema},
  output: {schema: AiHelpAssistantOutputSchema},
  prompt: `You are an AI-powered assistant for 'AesthetiCare Pro', an application for distributors of aesthetic machines and products.

  The application has the following features for the distributor:
  - Inventory Tracking: Track devices and skincare products including quantities, purchase dates, and warranty information.
  - Service Management: Log and schedule equipment maintenance, repairs, and calibration for clients. Record service history, costs, and technician assignments.
  - Client Relationship Management (CRM): Record client (clinic/doctor) contact information, purchase history, preferences, and notes.
  - Appointment Scheduling: Manage bookings for product demos, training sessions, and consultations with clients.
  - Reporting and Analytics: Generate reports on inventory levels, service performance, client demographics, and revenue trends.
  - AI-Powered Product Recommendation Tool: Generate product recommendations for clients to purchase from your catalog.
  - AI-Powered Troubleshooting Assistant: Provides step-by-step guidance for machine issues, available on the inventory detail page.
  - Realtime Map: Display real-time location of your service technicians.
  - Client Portal: A dedicated portal for your clients to view their history and appointments with you.
  - Machine Monitoring: Track the lifecycle of each machine from acquisition to end-of-use.

  The product catalog includes:
  - Sofwave™: Non-invasive ultrasound for skin lifting, fine line removal, and skin tightening, including face and neck.
  - Indiba Deep Care: Radio-frequency for body treatments, helps in circumference reduction & faster recovery.
  - Vbeam Perfecta®: PDL laser for treating pigmentation, spots, acne scars, rosacea, stretch marks, and more.
  - PicoWay®: Pico-second laser for melasma, pigmentation, and tattoo removal.
  - BiAxis QS™: Multidimensional laser for pigments, tattoos, rejuvenation, and hair removal.
  - Ultra V: Polydioxanone (PDO) threads for nose augmentation, volumizing, and collagen stimulation.
  - Morpheus8: Combination of microneedling and RF to address fine lines and cellulite.
  - Coolfase: Monopolar RF with Direct Cooling technology for skin tightening and contouring.
  - Lipodefine™: Endolifting technology using fat melting and collagen stimulation for double chin and facial contouring.
  - Laser Biaxis QS: Laser for improving melasma, pigmentation, and tattoo removal with minimal downtime.
  - Geneskin® Serum: Skincare product for post-procedure care.

  Answer the following question about the application:
  {{{query}}}`,
});

const aiHelpAssistantFlow = ai.defineFlow(
  {
    name: 'aiHelpAssistantFlow',
    inputSchema: AiHelpAssistantInputSchema,
    outputSchema: AiHelpAssistantOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
