// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview An AI-powered assistant to answer user questions about the application.
 *
 * - aiHelpAssistant - A function that provides guidance and answers questions about the application.
 * - AiHelpAssistantInput - The input type for the aiHelpAssistant function.
 * - AiHelpAssistantOutput - The return type for the aiHelpAssistant function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AiHelpAssistantInputSchema = z.object({
  query: z.string().describe('The user query about the application.'),
});
export type AiHelpAssistantInput = z.infer<typeof AiHelpAssistantInputSchema>;

const AiHelpAssistantOutputSchema = z.object({
  answer: z.string().describe('The answer to the user query.'),
});
export type AiHelpAssistantOutput = z.infer<typeof AiHelpAssistantOutputSchema>;

export async function aiHelpAssistant(input: AiHelpAssistantInput): Promise<AiHelpAssistantOutput> {
  return aiHelpAssistantFlow(input);
}

const prompt = ai.definePrompt({
  name: 'aiHelpAssistantPrompt',
  input: {schema: AiHelpAssistantInputSchema},
  output: {schema: AiHelpAssistantOutputSchema},
  prompt: `You are an AI-powered assistant for 'AesthetiCare Pro', an application for distributors of aesthetic machines and products.

  The application has the following features for the distributor:
  - Inventory Tracking: Track devices and skincare products including quantities, purchase dates, and warranty information.
  - Service Management: Log and schedule equipment maintenance, repairs, and calibration for clients. Record service history, costs, and technician assignments.
  - Client Relationship Management (CRM): Record client (clinic/doctor) contact information, purchase history, preferences, and notes.
  - Appointment Scheduling: Manage bookings for product demos, training sessions, and consultations with clients.
  - Reporting and Analytics: Generate reports on inventory levels, service performance, client demographics, and revenue trends.
  - AI-Powered Product Recommendation Tool: Generate product recommendations for clients to purchase from your catalog.
  - AI-Powered Troubleshooting Assistant: Provides step-by-step guidance for machine issues, available on the inventory detail page.
  - Realtime Map: Display real-time location of your service technicians.
  - Client Portal: A dedicated portal for your clients to view their history and appointments with you. Clients can request service or troubleshoot issues with their machines directly from this portal.
  - Machine Monitoring: Track the lifecycle of each machine from acquisition to end-of-use.

  The product catalog includes:
  - PicoWay® (by Candela), BiAxis Pico™ (by BiAxis): Picosecond Laser for pigmentation (melasma, nevi), tattoo removal, and collagen remodeling.
  - Vbeam Perfecta® (by Candela): Pulsed-Dye Laser (PDL) for rosacea, vascular issues, pigmentation, acne scars, and keloids.
  - BiAxis QS™ (by BiAxis): Q-switched Laser for acne scars, freckles, pigmentation, and tattoo removal.
  - Frax Pro (by Ellipse / Candela): Non-ablative fractional laser for skin resurfacing, improving texture, and collagen stimulation.
  - Morpheus8 (by InMode): RF Microneedling for wrinkles, skin laxity, and cellulite.
  - Sofwave™ (by Sofwave Medical): 3D Ultrasound for face/neck lifting, fine lines, and cellulite.
  - Indiba Deep Care (by INDIBA®): Radio Frequency for body contouring, cellulite, post-surgery care, and circumference reduction.
  - Divine Pro (by Pollogen / Lumenis): Multi-treatment platform for facial rejuvenation, dermal volumizing, and skin firming.
  - OxyGeneo & Pollogen (by Pollogen / Lumenis): Combines Oxygenation, RF, and Ultrasound for skin brightening, pigmentation, and anti-aging.
  - Geneskin® Serum: Skincare product for post-procedure care.
  - Other skincare products like cleansers and creams.

  Answer the following question about the application:
  {{{query}}}`,
});

const aiHelpAssistantFlow = ai.defineFlow(
  {
    name: 'aiHelpAssistantFlow',
    inputSchema: AiHelpAssistantInputSchema,
    outputSchema: AiHelpAssistantOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
