// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview An AI-powered assistant to answer user questions about the application.
 *
 * - aiHelpAssistant - A function that provides guidance and answers questions about the application.
 * - AiHelpAssistantInput - The input type for the aiHelpAssistant function.
 * - AiHelpAssistantOutput - The return type for the aiHelpAssistant function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AiHelpAssistantInputSchema = z.object({
  query: z.string().describe('The user query about the application.'),
});
export type AiHelpAssistantInput = z.infer<typeof AiHelpAssistantInputSchema>;

const AiHelpAssistantOutputSchema = z.object({
  answer: z.string().describe('The answer to the user query.'),
});
export type AiHelpAssistantOutput = z.infer<typeof AiHelpAssistantOutputSchema>;

export async function aiHelpAssistant(input: AiHelpAssistantInput): Promise<AiHelpAssistantOutput> {
  return aiHelpAssistantFlow(input);
}

const prompt = ai.definePrompt({
  name: 'aiHelpAssistantPrompt',
  input: {schema: AiHelpAssistantInputSchema},
  output: {schema: AiHelpAssistantOutputSchema},
  prompt: `You are an AI-powered assistant designed to answer user questions about the Serenity AesthetiCare Hub application.

  The application has the following features:
  - Inventory Tracking: Track devices and skincare products (Sofwave™, Vbeam Perfecta®, Geneskin®, etc.) including quantities, purchase dates, warranty, and maintenance schedules.
  - Service Management: Log and schedule equipment maintenance, repairs, and calibration. Record service history, costs, and technician assignments.
  - Client Relationship Management (CRM): Record client contact information, aesthetic treatment history, preferences, and consent forms.
  - Appointment Scheduling: Manage bookings for consultations, treatments, and follow-up appointments.
  - Reporting and Analytics: Generate reports on inventory levels, service performance, client demographics, and revenue trends.
  - AI-Powered Product Recommendation Tool: Generate product recommendations based on treatment history.
  - Realtime Map: Display real-time location of service technicians.

  Answer the following question about the application:
  {{{query}}}`,
});

const aiHelpAssistantFlow = ai.defineFlow(
  {
    name: 'aiHelpAssistantFlow',
    inputSchema: AiHelpAssistantInputSchema,
    outputSchema: AiHelpAssistantOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
