import type {
  AdminUser,
  InventoryItem,
  ServiceRecord,
  Client,
  Appointment,
  ClientRequest,
} from '@/types';

export const adminUsers: AdminUser[] = [
  {
    id: 1,
    name: 'Admin User',
    email: 'admin@aestheticare.pro',
    avatar: 'https://placehold.co/100x100.png',
  },
];

export const inventory: InventoryItem[] = [
  {
    id: 'inv-001',
    name: 'PicoWay®',
    type: 'Device',
    quantity: 5,
    purchase_date: '2023-01-15',
    warranty_end_date: '2025-01-15',
    status: 'In Stock',
    image_url: 'https://aspmedica.com/wp-content/uploads/2021/11/picoway-resolve-fusion-532-1.png',
    description: 'Picosecond Laser for pigmentation, tattoo removal, and collagen remodeling. Advanced technology by Candela.',
    client_id: 'cli-001'
  },
  {
    id: 'inv-002',
    name: 'Vbeam Perfecta®',
    type: 'Device',
    quantity: 8,
    purchase_date: '2022-11-20',
    warranty_end_date: '2024-11-20',
    status: 'In Stock',
    image_url: 'https://aspmedica.com/wp-content/uploads/2022/07/vbeam-perfecta.png',
    description: 'Pulsed-Dye Laser (PDL) for rosacea, vascular issues, and pigmentation. Gold standard for vascular treatments.',
    client_id: 'cli-002'
  },
  {
    id: 'inv-003',
    name: 'Morpheus8',
    type: 'Device',
    quantity: 3,
    purchase_date: '2023-05-10',
    warranty_end_date: '2025-05-10',
    status: 'In Stock',
    image_url: 'https://aspmedica.com/wp-content/uploads/2022/07/morpheus8.png',
    description: 'RF Microneedling device for wrinkles, skin laxity, and cellulite. Deep fractional remodeling.',
    client_id: 'cli-001'
  },
  {
    id: 'inv-004',
    name: 'Geneskin® Serum',
    type: 'Skincare',
    quantity: 50,
    purchase_date: '2024-03-01',
    warranty_end_date: 'N/A',
    status: 'In Stock',
    image_url: 'https://placehold.co/600x400.png',
    description: 'Post-procedure serum to enhance recovery and results. Contains growth factors and hyaluronic acid.',
  },
  {
    id: 'inv-005',
    name: 'Sofwave™',
    type: 'Device',
    quantity: 2,
    purchase_date: '2023-08-22',
    warranty_end_date: '2025-08-22',
    status: 'Low Stock',
    image_url: 'https://aspmedica.com/wp-content/uploads/2022/07/sofwave.png',
    description: '3D Ultrasound for face/neck lifting and fine lines. Non-invasive with zero downtime.',
    client_id: 'cli-003'
  },
  {
    id: 'inv-006',
    name: 'Indiba Deep Care',
    type: 'Device',
    quantity: 0,
    purchase_date: '2022-09-05',
    warranty_end_date: '2024-09-05',
    status: 'Out of Stock',
    image_url: 'https://aspmedica.com/wp-content/uploads/2022/07/indiba.png',
    description: 'Radio Frequency for body contouring, cellulite, and post-surgery care.',
  },
];

export const serviceRecords: ServiceRecord[] = [
  {
    id: 'ser-001',
    equipment: 'PicoWay®',
    service_type: 'Maintenance',
    date: '2024-05-10',
    technician: 'Ahmad Susanto',
    cost: 250,
    status: 'Completed',
    client_name: 'Dermaster Clinic',
    client_location: 'Jl. Melawai Raya No.1, Jakarta Selatan',
    problem_identification: 'Routine annual maintenance and system check-up.',
    solution: 'Cleaned optics, calibrated laser output, and updated software to the latest version. All systems are nominal.',
    duration: '4 hours',
    technician_notes: 'Device is in excellent condition. Recommended next check-up in 6 months.',
  },
  {
    id: 'ser-002',
    equipment: 'Vbeam Perfecta®',
    service_type: 'Repair',
    date: '2024-05-20',
    technician: 'Budi Hartono',
    cost: 750,
    status: 'In Progress',
    client_name: 'Miracle Aesthetic Clinic',
    client_location: 'Jl. Asia Afrika No. 8, Bandung',
    problem_identification: 'Error code 503 - Unstable energy output reported by the client.',
    solution: 'Identified a faulty power supply unit. Replacement part has been ordered and is pending installation.',
    duration: '2 days (ongoing)',
  },
  {
    id: 'ser-003',
    equipment: 'Morpheus8',
    service_type: 'Calibration',
    date: '2024-06-01',
    technician: 'Ahmad Susanto',
    cost: 300,
    status: 'Scheduled',
    client_name: 'Dermaster Clinic',
    client_location: 'Jl. Melawai Raya No.1, Jakarta Selatan',
    problem_identification: 'Scheduled 6-month calibration for RF energy levels.',
    solution: 'N/A',
    duration: '3 hours',
  },
];

export const clients: Client[] = [
  {
    id: 'cli-001',
    name: 'Dermaster Clinic',
    email: 'info@dermaster.com',
    phone: '021-555-1111',
    join_date: '2022-01-20',
    avatar: 'https://placehold.co/100x100.png',
    penanggung_jawab: {
      nama: 'Dr. Andreas',
      jabatan: 'Kepala Cabang',
    },
    treatment_history: 'Fokus utama pada perawatan laser untuk pigmentasi dan peremajaan. Telah membeli PicoWay dan Morpheus8. Menunjukkan minat pada teknologi ultrasound untuk face lifting.',
    preferences: ['Laser Pigmentation', 'RF Microneedling', 'Skincare'],
    location: {
      address: 'Jl. Melawai Raya No.1, Melawai, Kec. Kby. Baru, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12160',
      lat: -6.2458,
      lng: 106.7992,
    },
  },
  {
    id: 'cli-002',
    name: 'Miracle Aesthetic Clinic',
    email: 'contact@miracle-clinic.com',
    phone: '022-420-9 Miracle',
    join_date: '2021-08-15',
    avatar: 'https://placehold.co/100x100.png',
    penanggung_jawab: {
      nama: 'Dr. Lanny Juniarti',
      jabatan: 'Founder & President Director',
    },
    treatment_history: 'Klien lama dengan fokus pada berbagai macam perawatan estetika. Memiliki beberapa perangkat dari berbagai distributor. Baru-baru ini membeli Vbeam Perfecta untuk perawatan vaskular.',
    preferences: ['Vascular Laser', 'Body Contouring', 'Anti-Aging'],
    location: {
      address: 'Jl. Asia Afrika No.8, Kb. Pisang, Kec. Sumur Bandung, Kota Bandung, Jawa Barat 40261',
      lat: -6.9217,
      lng: 107.6071,
    },
  },
  {
    id: 'cli-003',
    name: 'Zap Clinic',
    email: 'info@zap.co.id',
    phone: '1500-310',
    join_date: '2023-03-10',
    avatar: 'https://placehold.co/100x100.png',
    penanggung_jawab: {
      nama: 'Fadli Sahab',
      jabatan: 'Chief Executive Officer',
    },
    treatment_history: 'Jaringan klinik besar yang berfokus pada hair removal dan perawatan photo facial. Telah membeli perangkat Sofwave untuk layanan premium face lifting non-invasif.',
    preferences: ['Hair Removal', 'Ultrasound Lifting', 'Photo Facial'],
    location: {
      address: 'Jl. Suryo No.30, Rw. Bar., Kec. Kby. Baru, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12180',
      lat: -6.2393,
      lng: 106.8122,
    },
  },
];

export const appointments: Appointment[] = [
  {
    id: 'apt-001',
    client_name: 'Dermaster Clinic',
    client_id: 'cli-001',
    service: 'Sofwave™ Demo',
    date: '2024-07-15',
    time: '10:00 AM',
    status: 'Confirmed',
  },
  {
    id: 'apt-002',
    client_name: 'Miracle Aesthetic Clinic',
    client_id: 'cli-002',
    service: 'Vbeam Perfecta® Advanced Training',
    date: '2024-07-22',
    time: '02:00 PM',
    status: 'Pending',
  },
  {
    id: 'apt-003',
    client_name: 'Zap Clinic',
    client_id: 'cli-003',
    service: 'Quarterly Business Review',
    date: '2024-06-30',
    time: '11:00 AM',
    status: 'Confirmed',
  },
    {
    id: 'apt-004',
    client_name: 'Dermaster Clinic',
    client_id: 'cli-001',
    service: 'Morpheus8 Follow-up Training',
    date: '2024-05-28',
    time: '01:00 PM',
    status: 'Cancelled',
  },
];

export const clientRequests: ClientRequest[] = [
  {
    id: 'req-001',
    client_id: 'cli-002',
    client_name: 'Miracle Aesthetic Clinic',
    request_type: 'Service',
    details: 'Vbeam Perfecta showing error 503, requires technician.',
    status: 'In Progress',
    date: '2024-05-19',
  },
  {
    id: 'req-002',
    client_id: 'cli-001',
    client_name: 'Dermaster Clinic',
    request_type: 'Inquiry',
    details: 'Asking about bulk pricing for Geneskin® Serum.',
    status: 'New',
    date: '2024-05-21',
  },
  {
    id: 'req-003',
    client_id: 'cli-003',
    client_name: 'Zap Clinic',
    request_type: 'Troubleshoot',
    details: 'Sofwave handpiece not being detected by the main unit.',
    status: 'Resolved',
    date: '2024-05-15',
  },
];
